### ISSUE TITLE
Sequencing type bug

### ISSUE THREAD

**Issue by Bohdan-Khomtchouk** [Bohdan-Khomtchouk/Biochat#4]
Going to https://www.ncbi.nlm.nih.gov/sites/GDSbrowser?acc=GDS651 and clicking on the hyperlinked GPL570 leads to a page that says: "Technology type: in situ oligonucleotide" which should be coded as microarray.  Currently, GDS651 returns `Sequencing type: other`, whereas it should be `microarray`.

**Comment by vseloved** [comment]
It seems that all GDS's are microarray, so this will be hardcoded
